-- Anonymous public assessment journey telemetry.
-- Proposal text, organisation, revenue, scores and local decision records are never sent.

create table if not exists public.bvf_journey_events (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  event_name text not null check (event_name = any (array[
    'assessment_started',
    'verdict_returned',
    'improvement_plan_opened',
    'decision_record_saved',
    'rescore_due',
    'assessment_rescored',
    'feedback_submitted'
  ])),
  journey_hash text not null check (char_length(journey_hash) between 8 and 24),
  session_hash text not null check (char_length(session_hash) between 8 and 24),
  entry_route text not null default 'web' check (char_length(entry_route) between 1 and 40),
  protocol_version text not null default '1.0' check (char_length(protocol_version) between 1 and 20),
  classification text check (classification is null or classification = any (array['Accelerate', 'Fix', 'Stop'])),
  feedback_response text check (feedback_response is null or feedback_response = any (array['Yes', 'Partly', 'No'])),
  feedback_more text check (feedback_more is null or char_length(feedback_more) <= 1000),
  feedback_stop text check (feedback_stop is null or char_length(feedback_stop) <= 1000),
  rescore_due date
);

create index if not exists bvf_journey_events_ts_idx on public.bvf_journey_events (ts desc);
create index if not exists bvf_journey_events_journey_idx on public.bvf_journey_events (journey_hash, ts desc);
create index if not exists bvf_journey_events_event_idx on public.bvf_journey_events (event_name, ts desc);

alter table public.bvf_journey_events enable row level security;

drop policy if exists "anonymous journey insert" on public.bvf_journey_events;
create policy "anonymous journey insert"
  on public.bvf_journey_events
  for insert
  to anon, authenticated
  with check (true);

revoke all on table public.bvf_journey_events from anon, authenticated;
grant insert on table public.bvf_journey_events to anon, authenticated;
grant usage, select on sequence public.bvf_journey_events_id_seq to anon, authenticated;

comment on table public.bvf_journey_events is
  'Anonymous AI BVF public journey events. Public roles may insert but cannot read. Assessment content remains in the browser.';
